config/routes.rb
Rails.application.routes.draw do

  get 'user/:user_id', to: 'user#show', as: 'user'

  get 'gossip/:gossip_id', to: 'gossip#view', as:'gossip'

   root 'home#index'

  get 'welcome/:id', to: 'welcome#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'team/', to: 'team#show'

  get 'contact/', to: 'contact#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	belongs_to :user, optional: true
	has_many :links
	has_many :tags, through: :links #Un gossip peut avoir plusieurs tags
end

app/models/link.rb
class Link < ApplicationRecord
	belongs_to :gossip, optional: true
	belongs_to :tag, optional: true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
	belongs_to :sender, class_name: 'User'
	belongs_to :recipient, class_name: 'User'
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :links
	has_many :gossips, through: :links 

end

app/models/user.rb
class User < ApplicationRecord
	belongs_to :city, optional: true
	has_many :gossips
	has_many :sent_messages, foreign_key: 'sender_id', class_name: 'PrivateMessage'
	has_many :received_messages, foreign_key: 'recipient_id', class_name: 'PrivateMessage'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
	def show

	end
end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController
  def view

 @gossip = Gossip.find(params['gossip_id'])

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	
  end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
	def show

	end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
  	@user = User.find(params['user_id'])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def show
  	@first_name = params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contact/show.html.erb
<h3>Contactez nous :</h3>

<p>Jb : <span id="num">06 73 75 50 01</span></p>
<p>Hugo : <span id="num">07 86 83 11 79</span></p>

app/views/gossip/view.html.erb
<h1>Voici le gossip de : <%=@gossip.user.first_name%> <%=@gossip.user.last_name%></h1>
<%=link_to "Lien vers l'auteur", user_path(@gossip.user_id)%>
<br>
<br>
<p>Sont titre : <%=@gossip.title%></p>
<p>Son contenu : <%=@gossip.content%></p>
<p>Date de création : <%=@gossip.created_at%></p>
<p></p>

app/views/home/index.html.erb
<link rel="stylesheet" type="text/css" href="../assets/stylesheets/home.css">
<div class="body">
<center><h1>Welcome sur cette magnifique page !</h1></center>
<br>
<h6>Voici tout les potins en base :</h6>

<p><%Gossip.all.each do |g|%>
			
<div class="card" style="width: 18rem;margin: 3px;">
  <div class="card-body">
    <h5 class="card-title">Auteur : <%=g.user.first_name%></h5>
    <h6 class="card-subtitle mb-2 text-muted">Titre : <%=g.title%></h6>
    <p class="card-text">Clique sur le lien en dessous pour voir leur contenu</p>
    <center><a href="<%=gossip_path(g.id)%>" class="card-link">Gossip Link</a></center>
  </div>
</div>

<%end%></p>
</div>

app/views/team/show.html.erb
<h1>Voici la team de folie :</h1>

<h4>Mr. DEMENET Jean-Baptiste</h4>
<h4>MR. CORDILLOT Hugo</h4>

app/views/user/show.html.erb
<h1>Auteur : <%=@user.first_name%> <%=@user.last_name%></h1>
<p><%=@user.age%> ans</p>
<p><%=@user.email%></p>
<p><%=@user.city.name%></p>
<br>
<blockquote><span>"<%=@user.description%>"</span></blockquote>

app/views/welcome/show.html.erb
<h1>Welcome <%=@first_name%> !</h1>
<br>
<p>Ici c'est notre super site de potins, il est chouette, non ?</p>