config/routes.rb
Rails.application.routes.draw do

  get 'user/:user_id', to: 'user#show', as: 'user'

  get 'gossip/:gossip_id', to: 'gossip#view', as:'gossip'

   root 'home#index'

  get 'welcome/:id', to: 'welcome#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'team/', to: 'team#show'

  get 'contact/', to: 'contact#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	belongs_to :user, optional: true
	has_many :links
	has_many :tags, through: :links #Un gossip peut avoir plusieurs tags
end

app/models/link.rb
class Link < ApplicationRecord
	belongs_to :gossip, optional: true
	belongs_to :tag, optional: true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
	belongs_to :sender, class_name: 'User'
	belongs_to :recipient, class_name: 'User'
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :links
	has_many :gossips, through: :links 

end

app/models/user.rb
class User < ApplicationRecord
	belongs_to :city, optional: true
	has_many :gossips
	has_many :sent_messages, foreign_key: 'sender_id', class_name: 'PrivateMessage'
	has_many :received_messages, foreign_key: 'recipient_id', class_name: 'PrivateMessage'
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
	def show

	end
end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController
  def view

 @gossip = Gossip.find(params['gossip_id'])

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	
  end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
	def show

	end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
  	@user = User.find(params['user_id'])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def show
  	@first_name = params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js">
    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%=root_path%>">The Gossip Project</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="<%=root_path%>">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%=team_path%>">Team</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%=contact_path%>">Contact</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown link
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>
  </div>
</nav>
  <div class="yield">
    <%= yield %>
   </div> 
  </body>
</html>